name: FastAttentionXML


level: 2
k: 64
top: 15

model:
  hidden_size: 256
  layers_num: 1
  linear_size: [256]
  dropout: 0.5
  emb_trainable: False

cluster:
  max_leaf: 64
  eps: 1e-4
  levels: [5]

train:
  batch_size: 40
  nb_epoch: 30
  swa_warmup: 10

valid:
  batch_size: 40

predict:
  batch_size: 40

path: models
